# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [221]:
import pandas as pd
import plotly.express as px

# Notebook Presentation

In [222]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [223]:
df_apps = pd.read_csv('apps.csv')

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

In [224]:
df_apps.shape

(10841, 12)

In [225]:
df_apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres', 'Last_Updated', 'Android_Ver'],
      dtype='object')

In [226]:
df_apps.sample(n=5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
5857,BL 女性向け恋愛ゲーム◆俺プリクロス,FAMILY,4.20,3379,62.00,"100,000",Free,0,Mature 17+,Simulation,"March 23, 2017",2.3.3 and up
5111,Business Calendar Pro,PRODUCTIVITY,4.60,27135,4.00,"100,000",Paid,$4.99,Everyone,Productivity,"May 24, 2018",Varies with device
4880,Grand Stickman Cover V,GAME,4.00,1744,37.00,"100,000",Free,0,Mature 17+,Action,"May 19, 2018",4.1 and up
2293,Hospitalist Handbook,MEDICAL,4.80,12,18.00,"1,000",Paid,$19.99,Everyone,Medical,"June 5, 2017",4.1 and up
10629,Pokémon GO,GAME,4.10,10421284,85.00,"100,000,000",Free,0,Everyone,Adventure,"July 23, 2018",4.4 and up

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [227]:
df_apps.drop(['Last_Updated', 'Android_Ver'], axis=1, inplace=True)
df_apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres'],
      dtype='object')

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [228]:
df_apps.Rating.isna().values.sum()

np.int64(1474)

In [229]:
df_clean_apps = df_apps.dropna().copy()
df_clean_apps.shape

(9367, 10)

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [230]:
df_clean_apps.duplicated().values.sum()

np.int64(476)

In [231]:
df_clean_apps.loc[df_clean_apps['App'] == "Instagram"]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10808,Instagram,SOCIAL,4.50,66577446,5.30,"1,000,000,000",Free,0,Teen,Social
10809,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10810,Instagram,SOCIAL,4.50,66509917,5.30,"1,000,000,000",Free,0,Teen,Social

In [232]:
df_clean_apps.drop_duplicates(inplace=True, subset=["App", "Type", "Price"])
df_clean_apps.loc[df_clean_apps['App'] == "Instagram"]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social

In [233]:
df_clean_apps.shape

(8199, 10)

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [234]:
df_clean_apps.sort_values('Rating', ascending=False).head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
1751,Spine- The dating app,DATING,5.00,5,9.30,500,Free,0,Teen,Dating
1761,Selfie With Champion AJ Style,PHOTOGRAPHY,5.00,2,7.50,500,Free,0,Everyone,Photography
1763,Ag Valley Cooperative,BUSINESS,5.00,6,74.00,500,Free,0,Everyone,Business
1769,Yazdani Cd Center EllahAbad Official App,FAMILY,5.00,8,3.80,500,Free,0,Everyone,Entertainment

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [235]:
largest_apps = df_clean_apps.Size_MBs.sort_values(ascending=False).index
df_clean_apps.loc[largest_apps]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
8719,Draft Simulator for FUT 18,SPORTS,4.60,162933,100.00,"5,000,000",Free,0,Everyone,Sports
8718,Mini Golf King - Multiplayer Game,GAME,4.50,531458,100.00,"5,000,000",Free,0,Everyone,Sports
10295,SimCity BuildIt,FAMILY,4.50,4218587,100.00,"50,000,000",Free,0,Everyone 10+,Simulation
9945,Ultimate Tennis,SPORTS,4.30,183004,100.00,"10,000,000",Free,0,Everyone,Sports
9944,Gangster Town: Vice District,FAMILY,4.30,65146,100.00,"10,000,000",Free,0,Mature 17+,Simulation
...,...,...,...,...,...,...,...,...,...,...
5798,ExDialer PRO Key,COMMUNICATION,4.50,5474,0.02,"100,000",Paid,$3.99,Everyone,Communication
2648,Ad Remove Plugin for App2SD,PRODUCTIVITY,4.10,66,0.02,"1,000",Paid,$1.29,Everyone,Productivity
2684,My baby firework (Remove ad),FAMILY,4.10,30,0.01,"1,000",Paid,$0.99,Everyone,Entertainment
7966,Market Update Helper,LIBRARIES_AND_DEMO,4.10,20145,0.01,"1,000,000",Free,0,Everyone,Libraries & Demo
4696,Essential Resources,LIBRARIES_AND_DEMO,4.60,237,0.01,"50,000",Free,0,Everyone,Libraries & Demo

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [236]:
most_reviews = df_clean_apps.Reviews.sort_values(ascending=False).index
df_clean_apps.loc[most_reviews][:50]
# df_clean_apps.sort_values('Reviews', ascending=False).head(50)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10805,Facebook,SOCIAL,4.10,78158306,5.30,"1,000,000,000",Free,0,Teen,Social
10785,WhatsApp Messenger,COMMUNICATION,4.40,69119316,3.50,"1,000,000,000",Free,0,Everyone,Communication
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10784,Messenger – Text and Video Chat for Free,COMMUNICATION,4.00,56642847,3.50,"1,000,000,000",Free,0,Everyone,Communication
10650,Clash of Clans,GAME,4.60,44891723,98.00,"100,000,000",Free,0,Everyone 10+,Strategy
10744,Clean Master- Space Cleaner & Antivirus,TOOLS,4.70,42916526,3.40,"500,000,000",Free,0,Everyone,Tools
10835,Subway Surfers,GAME,4.50,27722264,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10828,YouTube,VIDEO_PLAYERS,4.30,25655305,4.65,"1,000,000,000",Free,0,Teen,Video Players & Editors
10746,"Security Master - Antivirus, VPN, AppLock, Boo...",TOOLS,4.70,24900999,3.40,"500,000,000",Free,0,Everyone,Tools
10584,Clash Royale,GAME,4.60,23133508,97.00,"100,000,000",Free,0,Everyone 10+,Strategy
10763,Candy Crush Saga,GAME,4.40,22426677,74.00,"500,000,000",Free,0,Everyone,Casual
10770,UC Browser - Fast Download Private & Secure,COMMUNICATION,4.50,17712922,40.00,"500,000,000",Free,0,Teen,Communication
10735,Snapchat,SOCIAL,4.00,17014787,5.30,"500,000,000",Free,0,Teen,Social
10489,"360 Security - Free Antivirus, Booster, Cleaner",TOOLS,4.60,16771865,3.40,"100,000,000",Free,0,Everyone,Tools
10731,My Talking Tom,GAME,4.50,14891223,36.00,"500,000,000",Free,0,Everyone,Casual
10594,8 Ball Pool,GAME,4.50,14198297,52.00,"100,000,000",Free,0,Everyone,Sports
10302,DU Battery Saver - Battery Charger & Battery Life,TOOLS,4.50,13479633,14.00,"100,000,000",Free,0,Everyone,Tools
10354,BBM - Free Calls & Messages,COMMUNICATION,4.30,12842860,3.50,"100,000,000",Free,0,Everyone,Communication
10549,Cache Cleaner-DU Speed Booster (booster & clea...,TOOLS,4.50,12759663,15.00,"100,000,000",Free,0,Everyone,Tools
10757,Twitter,NEWS_AND_MAGAZINES,4.30,11667403,6.30,"500,000,000",Free,0,Mature 17+,News & Magazines
10721,Viber Messenger,COMMUNICATION,4.30,11334799,3.50,"500,000,000",Free,0,Everyone,Communication
10578,Shadow Fight 2,GAME,4.60,10979062,88.00,"100,000,000",Free,0,Everyone 10+,Action
10813,Google Photos,PHOTOGRAPHY,4.50,10858556,6.90,"1,000,000,000",Free,0,Everyone,Photography
10724,LINE: Free Calls & Messages,COMMUNICATION,4.20,10790289,3.50,"500,000,000",Free,0,Everyone,Communication
10717,Pou,GAME,4.30,10485308,24.00,"500,000,000",Free,0,Everyone,Casual
10792,Skype - free IM & video calls,COMMUNICATION,4.10,10484169,3.50,"1,000,000,000",Free,0,Everyone,Communication
10628,Pokémon GO,GAME,4.10,10424925,85.00,"100,000,000",Free,0,Everyone,Adventure
10388,Minion Rush: Despicable Me Official Game,GAME,4.50,10216538,36.00,"100,000,000",Free,0,Everyone 10+,Casual;Action & Adventure
10694,Yes day,GAME,4.50,10055521,94.00,"100,000,000",Free,0,Everyone,Casual
10695,Hay Day,FAMILY,4.50,10053186,94.00,"100,000,000",Free,0,Everyone,Casual
10644,Dream League Soccer 2018,GAME,4.60,9882639,74.00,"100,000,000",Free,0,Everyone,Sports
10696,My Talking Angela,GAME,4.50,9881829,99.00,"100,000,000",Free,0,Everyone,Casual
10660,VivaVideo - Video Editor & Photo Movie,VIDEO_PLAYERS,4.60,9879473,40.00,"100,000,000",Free,0,Teen,Video Players & Editors
10786,Google Chrome: Fast & Secure,COMMUNICATION,4.30,9642995,3.50,"1,000,000,000",Free,0,Everyone,Communication
10817,Maps - Navigate & Explore,TRAVEL_AND_LOCAL,4.30,9235155,12.00,"1,000,000,000",Free,0,Everyone,Travel & Local
10672,Hill Climb Racing,GAME,4.40,8923587,63.00,"100,000,000",Free,0,Everyone,Racing
10734,Facebook Lite,SOCIAL,4.30,8606259,5.30,"500,000,000",Free,0,Teen,Social
10649,Asphalt 8: Airborne,GAME,4.50,8389714,92.00,"100,000,000",Free,0,Teen,Racing
10699,Mobile Legends: Bang Bang,GAME,4.40,8219586,99.00,"100,000,000",Free,0,Teen,Action
10322,Battery Doctor-Battery Life Saver & Battery Co...,TOOLS,4.50,8190074,17.00,"100,000,000",Free,0,Everyone,Tools
10396,Piano Tiles 2™,GAME,4.70,8118880,36.00,"100,000,000",Free,0,Everyone,Arcade
10777,Temple Run 2,GAME,4.30,8118609,62.00,"500,000,000",Free,0,Everyone,Action
10822,Google,TOOLS,4.40,8033493,3.40,"1,000,000,000",Free,0,Everyone,Tools
10359,"Truecaller: Caller ID, SMS spam blocking & Dialer",COMMUNICATION,4.50,7820209,3.50,"100,000,000",Free,0,Everyone,Communication
10711,SHAREit - Transfer & Share,TOOLS,4.60,7790693,17.00,"500,000,000",Free,0,Everyone,Tools
10389,Sniper 3D Gun Shooter: Free Shooting Games - FPS,GAME,4.60,7671249,36.00,"100,000,000",Free,0,Mature 17+,Action
10676,Farm Heroes Saga,GAME,4.40,7614130,70.00,"100,000,000",Free,0,Everyone,Casual
10576,PicsArt Photo Studio: Collage Maker & Pic Editor,PHOTOGRAPHY,4.50,7594559,34.00,"100,000,000",Free,0,Teen,Photography
10461,"PhotoGrid: Video & Pic Collage Maker, Photo Ed...",PHOTOGRAPHY,4.60,7529865,6.90,"100,000,000",Free,0,Everyone,Photography
10502,GO Launcher - 3D parallax Themes & HD Wallpapers,PERSONALIZATION,4.50,7464996,6.15,"100,000,000",Free,0,Everyone,Personalization

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [237]:
ratings = df_clean_apps.Content_Rating.value_counts()
ratings

Content_Rating
Everyone           6621
Teen                912
Mature 17+          357
Everyone 10+        305
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [238]:
# Pie
fig = px.pie(labels=ratings.index,
values=ratings.values,
title="Content Rating",
names=ratings.index,
)
fig.update_traces(textposition='outside', textinfo='percent+label')

fig.show()

In [239]:
# Donut
fig = px.pie(labels=ratings.index,
values=ratings.values,
title="Content Rating",
names=ratings.index,
hole=0.6,
)
fig.update_traces(textposition='inside', textfont_size=15, textinfo='percent')

fig.show()

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install?

Check the datatype of the Installs column.

Count the number of apps at each level of installations.

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

In [240]:
df_clean_apps.dtypes # object = str

App                object
Category           object
Rating            float64
Reviews             int64
Size_MBs          float64
Installs           object
Type               object
Price              object
Content_Rating     object
Genres             object
dtype: object

In [241]:
df_clean_apps['Installs'] = df_clean_apps['Installs'].str.replace(',', '').astype(int).copy()
df_clean_apps['Installs']

21                1
28                1
47                1
82                5
99                5
            ...
10824    1000000000
10828    1000000000
10829    1000000000
10831    1000000000
10835    1000000000
Name: Installs, Length: 8199, dtype: int64

In [242]:
df_clean_apps.dtypes

App                object
Category           object
Rating            float64
Reviews             int64
Size_MBs          float64
Installs            int64
Type               object
Price              object
Content_Rating     object
Genres             object
dtype: object

In [243]:
df_clean_apps[["Installs", "App"]].groupby("Installs").count()

             App
Installs
1              3
5              9
10            69
50            56
100          303
500          199
1000         698
5000         425
10000        988
50000        457
100000      1096
500000       504
1000000     1417
5000000      607
10000000     933
50000000     202
100000000    189
500000000     24
1000000000    20

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

In [244]:
df_clean_apps['Price'] = df_clean_apps['Price'].str.replace('$', '')
df_clean_apps.Price = pd.to_numeric(df_clean_apps.Price)
df_clean_apps.sort_values('Price', ascending=False).head(20)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
3946,I'm Rich - Trump Edition,LIFESTYLE,3.60,275,7.30,10000,Paid,400.00,Everyone,Lifestyle
2394,I am Rich!,FINANCE,3.80,93,22.00,1000,Paid,399.99,Everyone,Finance
2461,I AM RICH PRO PLUS,FINANCE,4.00,36,41.00,1000,Paid,399.99,Everyone,Finance
1331,most expensive app (H),FAMILY,4.30,6,1.50,100,Paid,399.99,Everyone,Entertainment
3145,I am rich(premium),FINANCE,3.50,472,0.94,5000,Paid,399.99,Everyone,Finance
2775,I Am Rich Pro,FAMILY,4.40,201,2.70,5000,Paid,399.99,Everyone,Entertainment
5765,I am rich,LIFESTYLE,3.80,3547,1.80,100000,Paid,399.99,Everyone,Lifestyle
3221,I am Rich Plus,FAMILY,4.00,856,8.70,10000,Paid,399.99,Everyone,Entertainment
3554,💎 I'm rich,LIFESTYLE,3.80,718,26.00,10000,Paid,399.99,Everyone,Lifestyle
3114,I am Rich,FINANCE,4.30,180,3.80,5000,Paid,399.99,Everyone,Finance
4606,I Am Rich Premium,FINANCE,4.10,1867,4.70,50000,Paid,399.99,Everyone,Finance
1946,I am rich (Most expensive app),FINANCE,4.10,129,2.70,1000,Paid,399.99,Teen,Finance
3897,I Am Rich,FAMILY,3.60,217,4.90,10000,Paid,389.99,Everyone,Entertainment
2193,I am extremely Rich,LIFESTYLE,2.90,41,2.90,1000,Paid,379.99,Everyone,Lifestyle
3856,I am rich VIP,LIFESTYLE,3.80,411,2.60,10000,Paid,299.99,Everyone,Lifestyle
2281,Vargo Anesthesia Mega App,MEDICAL,4.60,92,32.00,1000,Paid,79.99,Everyone,Medical
1407,LTC AS Legal,MEDICAL,4.00,6,1.30,100,Paid,39.99,Everyone,Medical
2629,I am Rich Person,LIFESTYLE,4.20,134,1.80,1000,Paid,37.99,Everyone,Lifestyle
2481,A Manual of Acupuncture,MEDICAL,3.50,214,68.00,1000,Paid,33.99,Everyone,Medical
2207,EMT PASS,MEDICAL,3.40,51,2.40,1000,Paid,29.99,Everyone,Medical

### The most expensive apps sub $250

In [245]:
df_clean_apps.drop(df_clean_apps[df_clean_apps.Price > 250].index, inplace=True)
df_clean_apps.sort_values('Price', ascending=False).head(20)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
2281,Vargo Anesthesia Mega App,MEDICAL,4.60,92,32.00,1000,Paid,79.99,Everyone,Medical
1407,LTC AS Legal,MEDICAL,4.00,6,1.30,100,Paid,39.99,Everyone,Medical
2629,I am Rich Person,LIFESTYLE,4.20,134,1.80,1000,Paid,37.99,Everyone,Lifestyle
2481,A Manual of Acupuncture,MEDICAL,3.50,214,68.00,1000,Paid,33.99,Everyone,Medical
504,AP Art History Flashcards,FAMILY,5.00,1,96.00,10,Paid,29.99,Mature 17+,Education
2463,PTA Content Master,MEDICAL,4.20,64,41.00,1000,Paid,29.99,Everyone,Medical
2207,EMT PASS,MEDICAL,3.40,51,2.40,1000,Paid,29.99,Everyone,Medical
4264,Golfshot Plus: Golf GPS,SPORTS,4.10,3387,25.00,50000,Paid,29.99,Everyone,Sports
4772,Human Anatomy Atlas 2018: Complete 3D Human Body,MEDICAL,4.50,2921,25.00,100000,Paid,24.99,Everyone,Medical
3241,"Muscle Premium - Human Anatomy, Kinesiology, B...",MEDICAL,4.20,168,25.00,10000,Paid,24.99,Everyone,Medical
2293,Hospitalist Handbook,MEDICAL,4.80,12,18.00,1000,Paid,19.99,Everyone,Medical
4470,DRAGON QUEST VIII,FAMILY,4.50,7812,27.00,50000,Paid,19.99,Everyone 10+,Role Playing
526,USMLE Step 2 CK Flashcards,FAMILY,5.00,1,40.00,10,Paid,19.99,Everyone,Education
2119,NewTek NDI,PHOTOGRAPHY,3.50,77,1.20,1000,Paid,19.99,Everyone,Photography
2473,boattheory.ch Full 2018,FAMILY,4.70,54,50.00,1000,Paid,19.40,Everyone,Education
4090,I am Rich Premium Plus,FINANCE,4.60,459,2.00,10000,Paid,18.99,Everyone,Finance
3778,The World Ends With You,GAME,4.60,4108,13.00,10000,Paid,17.99,Everyone 10+,Arcade
1508,SkyTest BU/GU Lite,BUSINESS,2.90,28,20.00,500,Paid,17.99,Everyone,Business
3439,Trine 2: Complete Story,GAME,3.80,252,11.00,10000,Paid,16.99,Teen,Action
2603,2017 EMRA Antibiotic Guide,MEDICAL,4.40,12,3.80,1000,Paid,16.99,Everyone,Medical

### Highest Grossing Paid Apps (ballpark estimate)

In [246]:
revenue_estimate = df_clean_apps['Price'] * df_clean_apps['Installs']
df_clean_apps.insert(8, 'Revenue_Estimate', revenue_estimate)
df_clean_apps.sort_values("Revenue_Estimate", ascending=False).head(10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Revenue_Estimate,Content_Rating,Genres
9220,Minecraft,FAMILY,4.50,2376564,19.00,10000000,Paid,6.99,"69,900,000.00",Everyone 10+,Arcade;Action & Adventure
8825,Hitman Sniper,GAME,4.60,408292,29.00,10000000,Paid,0.99,"9,900,000.00",Mature 17+,Action
7151,Grand Theft Auto: San Andreas,GAME,4.40,348962,26.00,1000000,Paid,6.99,"6,990,000.00",Mature 17+,Action
7477,Facetune - For Free,PHOTOGRAPHY,4.40,49553,48.00,1000000,Paid,5.99,"5,990,000.00",Everyone,Photography
7977,Sleep as Android Unlock,LIFESTYLE,4.50,23966,0.85,1000000,Paid,5.99,"5,990,000.00",Everyone,Lifestyle
6594,DraStic DS Emulator,GAME,4.60,87766,12.00,1000000,Paid,4.99,"4,990,000.00",Everyone,Action
6082,Weather Live,WEATHER,4.50,76593,4.75,500000,Paid,5.99,"2,995,000.00",Everyone,Weather
6746,Card Wars - Adventure Time,FAMILY,4.30,129603,23.00,1000000,Paid,2.99,"2,990,000.00",Everyone 10+,Card;Action & Adventure
7633,Five Nights at Freddy's,GAME,4.60,100805,50.00,1000000,Paid,2.99,"2,990,000.00",Teen,Action
7954,Bloons TD 5,FAMILY,4.60,190086,94.00,1000000,Paid,2.99,"2,990,000.00",Everyone,Strategy

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

In [247]:
df_clean_apps.Category.nunique()

33

In [248]:
top10_category = df_clean_apps.Category.value_counts()[:10]
top10_category

Category
FAMILY             1606
GAME                910
TOOLS               719
PRODUCTIVITY        301
PERSONALIZATION     298
LIFESTYLE           297
FINANCE             296
MEDICAL             292
PHOTOGRAPHY         263
BUSINESS            262
Name: count, dtype: int64

In [249]:
bar = px.bar(x = top10_category.index, # index = category name
             y = top10_category.values)

bar.show()

### Vertical Bar Chart - Highest Competition (Number of Apps)

In [250]:
category_installs = df_clean_apps.groupby('Category').agg({'Installs': pd.Series.sum})
category_installs.sort_values('Installs', ascending=True, inplace=True)

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

In [251]:
h_bar = px.bar(x = category_installs.Installs,
               y = category_installs.index,
               orientation='h',
               title='Category Popularity')

h_bar.update_layout(xaxis_title='Number of Downloads', yaxis_title='Category')
h_bar.show()

In [252]:
category_concentration = df_clean_apps.groupby('Category').agg({'Installs': pd.Series.sum, 'App': pd.Series.count})
category_concentration.head()
category_concentration.shape

(33, 2)

### Category Concentration - Downloads vs. Competition

**Challenge**:
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this.

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

In [253]:
fig = px.scatter(category_concentration, x="App", y="Installs", color='Installs', size='App', hover_data=['Installs'], hover_name=category_concentration.index, width=1050, title="Category Concentration")
fig.update_layout(yaxis=dict(type='log'), xaxis_title="Number of Apps", yaxis_title="Installs", font=dict(size=14))
fig.show()

# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

In [254]:
stack = df_clean_apps.Genres.str.split(';', expand=True).stack()
genres = stack.value_counts()[:15]

# Colour Scales in Plotly Charts - Competition in Genres

In [255]:
bar = px.bar(x=genres.index, y=genres.values,
             title="Top Genres",
             color=genres.values, # Use the values of 'genres' to add color
             color_continuous_scale="Agsunset",
            )

# bar.update_coloraxes(showscale=False) # this..
bar.update_layout(xaxis_title="Genre", yaxis_title="Number of Apps", font=dict(size=14), coloraxis_showscale=False) # ..or add 'coloraxis_showscale' here
bar.show()

**Challenge**: Can you create this chart with the Series containing the genre data?

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/).

* Find a way to set the colour scale using the color_continuous_scale parameter.
* Find a way to make the color axis disappear by using coloraxis_showscale.

# Grouped Bar Charts: Free vs. Paid Apps per Category

In [256]:
df_free_vs_paid = df_clean_apps.groupby(["Category", "Type"], as_index=False).agg({'App': pd.Series.count})
df_free_vs_paid.head()

            Category  Type  App
0     ART_AND_DESIGN  Free   58
1     ART_AND_DESIGN  Paid    3
2  AUTO_AND_VEHICLES  Free   72
3  AUTO_AND_VEHICLES  Paid    1
4             BEAUTY  Free   42

**Challenge**: Use the plotly express bar [chart examples](https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories) and the [.bar() API reference](https://plotly.com/python-api-reference/generated/plotly.express.bar.html#plotly.express.bar) to create this bar chart:

<img src=https://imgur.com/LE0XCxA.png>

You'll want to use the `df_free_vs_paid` DataFrame that you created above that has the total number of free and paid apps per category.

See if you can figure out how to get the look above by changing the `categoryorder` to 'total descending' as outlined in the documentation here [here](https://plotly.com/python/categorical-axes/#automatically-sorting-categories-by-name-or-total-value).

In [257]:
fig = px.bar(df_free_vs_paid, x='Category', y='App',
             color='Type',  # Color based on the 'Subcategory'
             barmode='group',  # Group bars for the same category
             title="Free vs Paid Apps by Category"
             )
fig.update_layout(yaxis_title="Number of Apps", yaxis=dict(type='log'))
fig.update_xaxes(categoryorder='total descending')
fig.show()

# Plotly Box Plots: Lost Downloads for Paid Apps

**Challenge**: Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

Use the [Box Plots Guide](https://plotly.com/python/box-plots/) and the [.box API reference](https://plotly.com/python-api-reference/generated/plotly.express.box.html) to create the following chart.

<img src=https://imgur.com/uVsECT3.png>

In [258]:
fig = px.box(df_clean_apps, x="Type", y="Installs", color="Type", notched=True, width=1000, points="all", title='How Many Downloads are Paid Apps Giving Up?')
fig.update_layout(yaxis=dict(type='log'))
fig.show()

# Plotly Box Plots: Revenue by App Category

**Challenge**: See if you can generate the chart below:

<img src=https://imgur.com/v4CiNqX.png>

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

Hint: I've used 'min ascending' to sort the categories.

In [259]:
df_paid_apps = df_clean_apps.loc[df_clean_apps['Type'] == "Paid"]
fig = px.box(df_paid_apps, x="Category", y="Revenue_Estimate", title='How Much Can Paid Apps Earn?')
fig.update_layout(yaxis=dict(type='log'), xaxis={'categoryorder':'min ascending'})
fig.show()

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

**Challenge**: What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps. I recommend using `{categoryorder':'max descending'}` to sort the categories.

In [260]:
fig = px.box(df_paid_apps, y="Price", title='Average paid app pricing', width=1000)
fig.update_layout(yaxis=dict(type='log'))
fig.show()

In [261]:
fig = px.box(df_paid_apps, x="Category", y="Price", title='Price per Category')
fig.update_layout(yaxis=dict(type='log'), xaxis={'categoryorder':'max descending'})
fig.show()